### ISSUE TITLE
BE BUG: https://rhapp-backend.rhdevs.repl.co/social/posts allows posts to be created even without valid inputs

### ISSUE THREAD

**Issue by leonghuenweng** [rhdevs/rhapp#560]
#method: POST

#Example of invalid input:
{"userID":"",
"title":"",
"description":" ",
"ccaID":1,
"createdAt":1617609361,
"postPics":[],
"isOfficial":false,
"tags":[]}

#Response obtained (wrong)
{
    "message": {
        "_id": "61ed80e7490dd01ea6e493d3",
        "ccaID": 1,
        "createdAt": 1642954983,
        "description": " ",
        "isOfficial": false,
        "postPics": [],
        "tags": [],
        "title": "",
        "userID": ""
    }
}

**Comment by porckhop** [comment]
Have edited the validation data on 'Posts' collection and the code no longer have this error
