### ISSUE TITLE
BE BUG: https://rhapp-backend-devel.rhdevs.repl.co/facilities/bookings/<bookingID> does not return error message

### ISSUE THREAD

**Issue by eugenetaan** [rhdevs/rhapp#568]
When sending a PUT request to edit booking details, changing endTime to be earlier or equal to startTime does not return error message

**Comment by eugenetaan** [comment]
eg sample data

{
    "facilityID": 6,
    "eventName": "Test",
    "userID": "{{userStudentID}}",
    "startTime": 1670083200,
    "endTime": 	1670083200,
    "description": "Test",
    "repeat": 0
}

**Comment by ttheng3810** [comment]
An attempt to reproduce this bug using Postman does return an error message to me though.
![Screenshot from 2022-01-28 15-02-05](https://user-images.githubusercontent.com/81245678/151502283-e1410e82-4dac-482c-a3c0-a62e61b8bc9f.png)

**Comment by eugenetaan** [comment]
Then i guess it is fixed
