### ISSUE TITLE
[Clarification Needed]BE BUG:  https://rhapp-backend-devel.rhdevs.repl.co/social/profiles no authentication needed to edit profiles

### ISSUE THREAD

**Issue by eugenetaan** [rhdevs/rhapp#570]
No authentication needed to edit any profile (PUT request)

**Comment by woowenjun99** [comment]
I can attempt to fix this bug but just to clarify, do you need me to add in authentication?

**Comment by angnobel** [comment]
> 

Yes, please add in authenttication and update the documentation

**Comment by woowenjun99** [comment]
Fix in #617
