### ISSUE TITLE
[FE] Add all RFs into RHApp

### ISSUE THREAD

**Issue by marcus-ong-qy** [rhdevs/rhapp#689]
at `routes/Authentication/Signup/index.txt` hardcode such that we allow these RFs to signup for an account

TODO:
1. Add these usernames listed below (currently only evan's 'RFHTBS' is coded in)
2. Abstract the RF username checks to an array at the top of the file

RFs usernames:
Mr Ezra - EPHCSLE
Yu - BIEYHY
Darren - CEECSC
Mornin - EPHFM
Linda - GROLC
Tin - ISSNTT

** NOTE **
Branch out from `devel` and PR to `devel`

**Comment by woowenjun99** [comment]
Alternatively, you can just use postman and save the account into the database through the API. Just make sure you use the same SHA256 encryption to create an account, and not just plain text.
