### ISSUE TITLE
[FE] FEATURE Facilities Revamp - Calender to show >5 months

### ISSUE THREAD

**Issue by marcus-ong-qy** [rhdevs/rhapp#719]
Something like this:
<img width="148" alt="image" src="https://user-images.githubusercontent.com/75428027/197487830-a868bed7-8bee-4d77-a20e-5013e93388cf.png">

Features:
- Show year along with month
- Disable "Previous" button when viewing current month

**Comment by marcus-ong-qy** [comment]
Remembered that there is an intention to limit bookings to 5 months in advance, shall confirm

**Comment by Cikguseven** [comment]
Calendar has already been limited to 5 months in advance in `revamp/facilities`. Are there any other features to be implemented?

![image](https://user-images.githubusercontent.com/40373653/209472721-067709c2-c253-440e-83a2-2e15e1835dca.png)

**Comment by marcus-ong-qy** [comment]
> Calendar has already been limited to 5 months in advance in `revamp/facilities` branch. Are there any other features to be implemented?

Oh yeah just to clarify, I originally thought to change the calendar such that it becomes like that in the picture above, where you can access >5 months in advance. But I realised that they might have designed it intentionally to prevent ppl from booking more than 5 months in advance. So for now I shall close this issue and confirm first
