### ISSUE TITLE
[FE] Redesign - Facilities Revamp front page

### ISSUE THREAD

**Issue by marcus-ong-qy** [rhdevs/rhapp#771]
Replace current front page
![image](https://user-images.githubusercontent.com/75428027/211960829-b0e3f01f-8036-449c-bdf8-6079b961c712.png)

With this:
![photo_2023-01-12_10-20-14](https://user-images.githubusercontent.com/75428027/211960533-98a5aca3-8a5a-4a7b-8ea0-48802df23304.jpg)

Note:
- **Branch and merge from `devel`!!!**
- Make sure the page is responsive and look good for both mobile and desktop!

Tips and resources:
- [Figma file link](https://www.figma.com/file/LJAYgXzOnF9STZXDfg1wsX/Yu-An-(Copy)-with-new-2022-Facilities-Revamp-temp-Designs?node-id=106%3A1807&t=EZPC1OxPPC5qLNsY-1) (follow **Design 2**)
- How to import svg files to frontend code: **(Export the ICONS TO EXPORT in the figma file)**
![image](https://user-images.githubusercontent.com/75428027/211961217-1e7e4c49-84fa-45d0-b7b0-c5e6a67765cf.png)
- place svg logos into `src/assets/facilitiesLogos`, then import

**Comment by lokeshvasnik** [comment]
Okay I can do this lets get a try!
